name: Deploy Atlas

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: deploy-atlas-production
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          script: |
            set -euo pipefail
            BRANCH="${{ github.ref_name }}"
            cd "${{ secrets.DEPLOY_PATH }}"
            git fetch --all --prune
            git checkout "$BRANCH" || git checkout -b "$BRANCH" "origin/$BRANCH"
            git pull --ff-only origin "$BRANCH"
            docker compose up -d --build --remove-orphans
            docker compose ps
            docker compose exec -T atlas_app python -m compileall atlas_app
            docker compose exec -T atlas_app curl -fsS http://localhost:5000/health >/dev/null
